//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Data;

namespace CVProjectMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egitim
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Boþ Geçilemez")]
        public string Baslik { get; set; }
        public string AltBaslik1 { get; set; }
        public string AltBaslik2 { get; set; }
        public string GNO { get; set; }
        public string Tarih { get; set; }
    }
}
